---
title: "Workshop_4"
author: "Phoebe Hird"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r cars}
# install and load your packages
#install.packages("sf") 
#install.packages("terra")
#install.packages("tmap")


#load into R library
library(tidyverse)
library(sf) # simple features
library (terra) # for raster
library(tmap) # Thematic maps are geographical maps in which spatial data distributions are visualized
```

## 

```{r}
#load the copepod data into R studio
library(readr)
data <- read_csv("../data/data-for-course/copepods_raw.csv")
data
#getwd()
```
```{r}
# A tibble: 5,313 × 11
   silk_id segment_no latitude longitude sample_time_utc  project route vessel  
     <dbl>      <dbl>    <dbl>     <dbl> <chr>            <chr>   <chr> <chr>   
 1       1          1    -28.3      154. 26/06/2009 22:08 AusCPR  BRSY  ANL Win...
 2       1          5    -28.7      154. 26/06/2009 23:12 AusCPR  BRSY  ANL Win...
 3       1          9    -29.0      154. 27/06/2009 0:17  AusCPR  BRSY  ANL Win...
 4       1         13    -29.3      154. 27/06/2009 1:22  AusCPR  BRSY  ANL Win...
 5       1         17    -29.7      154. 27/06/2009 2:26  AusCPR  BRSY  ANL Win...
 6       1         18    -29.8      154. 27/06/2009 2:43  AusCPR  BRSY  ANL Win...
 7       1         26    -30.4      153. 27/06/2009 4:52  AusCPR  BRSY  ANL Win...
 8       1         30    -30.7      153. 27/06/2009 5:57  AusCPR  BRSY  ANL Win...
 9       1         33    -31.0      153. 27/06/2009 6:45  AusCPR  BRSY  ANL Win...
10       1         37    -31.3      153. 27/06/2009 7:50  AusCPR  BRSY  ANL Win...
# ... with 5,303 more rows, and 3 more variables: meanlong <dbl>, region <chr>,
#   richness_raw <dbl>
```

```{r}
library(ggplot2)
ggplot(dat) + 
  aes(x = longitude, y = latitude, color = richness_raw) +
  geom_point()
```
```{r}
ggplot(dat, aes(x = latitude, y = richness_raw)) + 
  stat_smooth() + 
  geom_point()
```
```{r}
sdat <- st_as_sf(dat, coords = c("longitude", "latitude"), 
                 crs = 4326)

```
```{r}
crs4326 <- st_crs(4326)
crs4326 # look at the whole CRS
crs4326$Name # pull out just the name of the crs
#[1]"WGS 84"

crs4326$wkt # crs in well-known text format
sdat


```
```{r}
plot(sdat["richness_raw"])
```
```{r}
plot(sdat)
```

```{r}
map <- tm_shape(sdat) + 
  tm_dots(col = "richness_raw")

```
```{r}
tmap_save(map, filename = "../output/Richness-map.png", 
          width = 600, height = 600)
```
```{r}
aus <- st_read("../data/data-for-course/spatial-data/Aussie/Aussie.shp")
```

```{r}
shelf <- st_read("../data/data-for-course/spatial-data/aus_shelf/aus_shelf.shp")

```
```{r}
tm_shape(shelf) + 
  tm_polygons()
```
```{r}
aus_map <- tm_shape(shelf, bbox = sdat) + 
  tm_polygons() +
  tm_shape(aus) + 
  tm_polygons() + 
  tm_shape(sdat) + 
  tm_dots("richness_raw",palette = "viridis")
  tmap_options(bg.color = "white", legend.text.color = "black")
   
```
```{r}
vignette('tmap-getstarted')
```
```{r}
tmap_save(aus_map, filename = "../output/Aus_copepod_map.png", 
          width = 600, height = 600)
```

